"""refresh token replaced_by

Revision ID: 90d64102f378
Revises: 89595aafe6e8
Create Date: 2026-09-18 15:24:33.853055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '90d64102f378'
down_revision: Union[str, Sequence[str], None] = '89595aafe6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('replaced_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'replaced_by_id')
    # ### end Alembic commands ###
